name:                ratsoc
version:             0.1.0.0
github:              "githubuser/ratsoc"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ratsoc#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Werror
- -Wredundant-constraints
- -fwarn-tabs

default-extensions:
- GHC2021  # https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/control.html#extension-GHC2021
- DataKinds
- DefaultSignatures
- DerivingStrategies
- DerivingVia
- FunctionalDependencies
- LambdaCase
- NoImplicitPrelude
- NoMonomorphismRestriction
- OverloadedStrings
- PackageImports
- QuasiQuotes
- RecordWildCards
- TemplateHaskell
- TupleSections
- TypeFamilies
- ViewPatterns

library:
  source-dirs: src
  dependencies:
    - relude

executables:
  ratsoc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ratsoc
    - relude
    - unliftio

tests:
  ratsoc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ratsoc
    - relude
    - hspec
    - hspec-expectations
    - QuickCheck
    - quickcheck-classes
    - quickcheck-instances
